// src/components/footer.component.tsx
import Image from "next/image";

export default function Footer() {
    return (<footer className="border-b border-white mt-auto bg-primary text-livid">
        <div className="grid grid-cols-4 gap-4">
            <ul>
                <li>
                    <a href="/">

                        <div className="text-white font-bold text-xl flex justify-between items-center">
                            <Image src="/logo_white.png" alt="Logo de Talent Hub" width={32} height={32}/>
                            <span>
                      Talent Hub
                  </span>
                        </div>
                    </a>
                </li>
                <li>
                    <p>
                        Réunissant passionnés d'art, de développement, de musique et bien plus encore
                    </p>
                </li>
                <li>
                    <a href="https://discord.talent-hub.fr"
                       target="_blank"
                       className="mt-20 px-5 py-2 bg-white hover:bg-gray-200 rounded-xl font-semibold text-black transition-colors duration-200">
                        Rejoindre l'aventure
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <h3 className="text-xl text-white font-semibold mb-5">Acceuil</h3>
                </li>
                <li>
                    Blog
                </li>
                <li>
                    Offres
                </li>
                <li>
                    Trombinoscope
                </li>
            </ul>
            <ul>
                <li>
                    <h3 className="text-xl text-white font-semibold mb-5">Retrouvez-nous</h3>
                </li>
                <li>Instagram</li>
                <li>Twitter</li>
                <li>LinkedIn</li>
                <li>Discord</li>
            </ul>
            <div>
                <a href="#">
                    <div className="text-livid px-5 py-3 font-semibold rounded-xl border border-livid">
                        Se connecter
                    </div>
                </a>
            </div>
        </div>
    </footer>);
}

// components/Footer.vue
<script setup lang="ts">

</script>

<template>
    <div>


        <footer class="bg-white z-50 ">
            <div class="mx-4 lg:mx-8  not-diagonalNew px-0 lg:px-16 pt-16 pb-4  lg:border-x lg:border-t rounded-lg ">
                <div class="md:flex md:justify-between">
                    <div class="mb-6  md:mb-0">
                        <span class="mr-30">
                            <Logo />
                            <p class="w-9/12 font-normal text-base text-gray-400 mt-6 mb-10">Réunissant passionnés d'art, de
                                développement, de musique et bien plus encore
                            </p>
                            <span>
                                <JoinButton text="Rejoindre l’aventure" />
                            </span>
                        </span>
                    </div>
                    <div class="grid grid-cols-1 gap-8 sm:gap-20 sm:grid-cols-3 pb-16">
                        <div>
                            <h2 class="mb-6 text-xl font-semibold text-gray-900 truncate mt-16 sm:mt-0">Accueil</h2>
                            <ul class="text-gray-500 dark:text-gray-400 font-medium">
                                <li class="mb-8 sm:mb-4 ">
                                    <a href="https://flowbite.com/" class="hover:underline ">Blog</a>
                                </li>
                                <li class="mb-8 sm:mb-4 ">
                                    <a href="https://tailwindcss.com/" class="hover:underline">Offres CSS</a>
                                </li>
                                <li>
                                    <a href="https://tailwindcss.com/" class="hover:underline">Trombinoscope</a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <h2 class="mb-6 text-xl font-semibold text-gray-900 overflow-visible mt-12 sm:mt-0">
                                Contactez-nous</h2>
                            <ul class="text-gray-500 dark:text-gray-400 font-medium">
                                <li class="mb-8 sm:mb-4">
                                    <a href="https://github.com/themesberg/flowbite" class="hover:underline ">Instagram</a>
                                </li>
                                <li class="mb-8 sm:mb-4">
                                    <a href="https://discord.gg/4eeurUVvTy" class="hover:underline">Facebook</a>
                                </li>
                                <li>
                                    <a href="https://discord.gg/4eeurUVvTy" class="hover:underline">Twitter</a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <h2 class="mb-6 text-xl font-semibold text-gray-900 truncate mt-16 sm:mt-0">
                                <Connecter />
                            </h2>

                        </div>
                    </div>
                </div>
                <hr class="my-6 border-slate-200 sm:mx-auto lg:my-8" />
                <div class="my-16 sm:my-0 sm:flex sm:items-center sm:justify-between">
                    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© Copyright 2023, Talent Hub.
                    </span>

                </div>
            </div>
        </footer>


    </div>
</template>

<style lang="css" scoped>
.not-diagonalNew {
    transform: skewY(0deg);
}
</style>
