// src/components/navbar.component.tsx
"use client";

import React, {useState} from "react";
import Link from "next/link";
import Image from "next/image";
import {SignedIn, SignedOut, UserButton} from "@clerk/nextjs";

export default function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    const toggle = () => setIsOpen(!isOpen);

    return (<header>
        <nav className="inline-flex justify-around w-full items-center pb-4">
            <Link href="/" className="mr-6 font-bold text-xl flex items-center gap-1">
                <Image src="/logo_white.png" alt="Talent Hub's logo in white version" width={32} height={32}/>
                <span>Talent Hub</span>
            </Link>
            <ul className="inline-flex items-center text-sm text-livid gap-5">
                <li className="mr-6">
                    <Link href="/blog" className="hover:text-white delay-75 duration-100 ease-in-out">Blog</Link>
                </li>
                <li className="mr-6">
                    <Link href="/offres" className="hover:text-white delay-75 duration-100 ease-in-out">Offres</Link>
                </li>
                <li className="mr-6">
                    <Link href="/trombinoscope"
                          className="hover:text-white delay-75 duration-100 ease-in-out">Trombinoscope</Link>
                </li>
            </ul>

            <SignedIn>
                <UserButton/>
            </SignedIn>

            <SignedOut>

                <Link href="/sign-in"
                      className="inline-flex justify-between hover:text-white delay-75 duration-100 ease-in-out text-livid text-sm">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                         stroke-linejoin="round" className="lucide lucide-fingerprint">
                        <path d="M2 12C2 6.5 6.5 2 12 2a10 10 0 0 1 8 4"></path>
                        <path d="M5 19.5C5.5 18 6 15 6 12c0-.7.12-1.37.34-2"></path>
                        <path d="M17.29 21.02c.12-.6.43-2.3.5-3.02"></path>
                        <path d="M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4"></path>
                        <path d="M8.65 22c.21-.66.45-1.32.57-2"></path>
                        <path d="M14 13.12c0 2.38 0 6.38-1 8.88"></path>
                        <path d="M2 16h.01"></path>
                        <path d="M21.8 16c.2-2 .131-5.354 0-6"></path>
                        <path d="M9 6.8a6 6 0 0 1 9 5.2c0 .47 0 1.17-.02 2"></path>
                    </svg>
                    <span className="ml-2">
                                Se connecter
                            </span>
                </Link>

            </SignedOut>
        </nav>
    </header>);
}

// components/Navbar.vue
<template>
  <div>
    <nav class="fixed w-full p-6 bg-white z-20">
      <div class="flex items-center justify-between sm:justify-around">
        <!-- Header logo -->
        <div class="ml-0 lg:ml-24">
          <Logo />
        </div>
        <!-- Navbar -->
        <div class="hidden md:block">
          <ul class="flex space-x-2 text-sm bg-slate-100 px-1 py-2 rounded">
            <li>
              <NuxtLink to="/" active-class="exactActiveClass" class="px-2 hoverClass">Blog
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/Offres" active-class="exactActiveClass " class="px-2 hoverClass">Offres</NuxtLink>
            </li>
            <li>
              <NuxtLink to="/Trombinoscope" active-class="exactActiveClass" class="px-2 hoverClass">Trombinoscope
              </NuxtLink>
            </li>
          </ul>
        </div>
        <div class="hidden md:block mr-24">
          <ul>
            <li>
              <Connecter />
            </li>
          </ul>
        </div>
        <!-- Mobile toggle -->
        <div class="md:hidden">
          <button @click="drawer">
            <svg width="27" height="9" viewBox="0 0 27 9" fill="none" xmlns="http://www.w3.org/2000/svg">
              <rect width="27" height="2" fill="black" />
              <rect x="4" y="7" width="23" height="2" fill="black" />
            </svg>
          </button>
        </div>
        <!-- Drawer Menu -->
        <aside
          class="p-5 pt-0 transform top-0 left-0 w-screen bg-white fixed h-full overflow-auto ease-in-out transition-all duration-300 z-30"
          :class="isOpen ? 'translate-x-0' : '-translate-x-full'">
          <div class="close">
            <button class="absolute top-0 right-0 mt-6 mr-4" @click="isOpen = false">
              <svg class="w-6 h-6" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                viewBox="0 0 24 24" stroke="currentColor">
                <path d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>
          </div>

          <span @click="isOpen = false" class="flex w-full items-center justify-between p-4 pl-0 border-b">
            <Logo />
            <Connecter />
            <span class=""></span>
          </span>

          <ul class="">
            <li>
              <NuxtLink to="/" @click="isOpen = false" class="my-8 inline-block text-xl font-medium">Blog</NuxtLink>
            </li>
            <li>
              <NuxtLink to="/Offres" @click="isOpen = false" class="my-8 inline-block text-xl font-medium">Offres
              </NuxtLink>
            </li>
            <li>
              <NuxtLink to="/Trombinoscope" @click="isOpen = false" class="my-8 inline-block text-xl font-medium">
                Trombinoscope</NuxtLink>
            </li>
          </ul>
          <div class="border-t"></div>
          <ul class="text-gray-500 dark:text-gray-400 font-medium mb-8">
            <li class="mt-16">
              <a href="https://github.com/themesberg/flowbite" class="hover:underline">Instagram</a>
            </li>
            <li class="mt-8 sm:mb-4">
              <a href="https://discord.gg/4eeurUVvTy" class="hover:underline">Facebook</a>
            </li>
            <li class="mt-8">
              <a href="https://discord.gg/4eeurUVvTy" class="hover:underline">Twitter</a>
            </li>
          </ul>
          <JoinButton text="Rejoindre l’aventure" />
        </aside>
      </div>
    </nav>
  </div>
</template>

<script>
export default {
  data() {
    return {
      isOpen: false,
    };
  },
  methods: {
    drawer() {
      this.isOpen = !this.isOpen;
    },
  },
  watch: {
    isOpen: {
      immediate: true,
      handler(isOpen) {
        if (process.client) {
          if (isOpen) document.body.style.setProperty("overflow", "hidden");
          else document.body.style.removeProperty("overflow");
        }
      },
    },
  },
  mounted() {
    document.addEventListener("keydown", (e) => {
      if (e.keyCode == 27 && this.isOpen) this.isOpen = false;
    });
  },
};
</script>
<style>
.exactActiveClass {
  font-weight: 500;
  background-color: #fff;
  padding-top: 0.25rem;
  padding-bottom: 0.25rem;
}

.hoverClass:hover {
  font-weight: 500;
  background-color: #fff;
  padding-top: 0.25rem;
  padding-bottom: 0.25rem;
}

.exactActiveClass:hover {
  font-weight: 500;
  background-color: #ffffff9c;
  padding-top: 0.25rem;
  padding-bottom: 0.25rem;
}
</style>
