// components/navbar.vue
<script lang="ts" setup>

</script>

<template>
  <nav class="flex justify-between px-20 py-10">

    <span>Talent Hub</span>

    <div class="flex justify-between gap-5 bg-slate-100 p-2 rounded-md child-hover:bg-white child:p-2 child:rounded-md child:transition-all child:duration-300 child:ease-in-out">
      <nuxt-link to="/blog">Blog</nuxt-link>
      <nuxt-link to="/offres">Offres</nuxt-link>
      <nuxt-link to="/trombinoscope">Trombinoscope</nuxt-link>
    </div>

    <Button variant="link" asChild>
      <nuxt-link to="/signin" class="flex gap-5"><LucideFingerprint/> Se connecter</nuxt-link>
    </Button>
  </nav>
</template>

// src/components/navbar.component.tsx
export default function Navbar() {
    return (
        <nav className="w-full flex flex-row justify-between px-10 py-5">
            <div className="text-livid">Talent Hub</div>
            <div>
                <ul className="flex flex-row justify-between gap-5 text-livid">
                    <li>Blog</li>
                    <li>Offres</li>
                    <li>Trombinoscope</li>
                </ul>
            </div>
            <div className="bg-white text-black p-3 font-semibold rounded-xl">
                Se connecter
            </div>
        </nav>
    );
}
